### PR TITLE
Update LARA share dialog to use autolaunch page and fullscreen scaling

### PR DESCRIPTION
**Pull request by pjanik**
Changes:
- switch default page to "autolaunch"
- add "autolaunch" / "launch" page checkbox
- add "fullscreen scaling" checkbox (it passes "scaling" URL param to doc-server, which modifies CODAP iframe to scale down and include fullscreen button)
- display inputs bases on page tyle (Launch Button Text for "launch" page, scaling for "autolaunch")
- cleanup and simplify some related code (e.g. `lara` state was redundant, it can be generated using other properties; simplify some event handlers, remove refs)

Screenshots:
screen shot 2018-03-23 at 16 45 11
screen shot 2018-03-23 at 16 45 18

@dougmartin or @kswenson, could you take a look? @dougmartin seems to be the main contributor, but @kswenson works on IS2 project. 😉

### CODE REVIEW

**Comment by ddamelin** [comment]
I didn't realize you would be in this code. If I had known I would have requested you also add the option to have the app=is URL parameter as a checkbox as well. This causes the parent visibility toggles to appear in graphs be default. We typically use this parameter for sensor-based experiments, simulations, and SageModeler documents. It can be added in to the CODAP server URL by hand, but it would be easier for non-technical people to just check a box to add it there.

**Comment by jsandoe** [comment]
This PR missed the CODAP build today. I hope that it is not urgent. I generally check that the CFM has no changes on master when I do a CODAP build. Thus, I didn't see this.

**Comment by ddamelin** [comment]
It's not urgent but would be good to get into the next build if possible.

**Comment by ddamelin** [comment]
@pjanik The name would be "display data visibility toggles on graphs" and it should be off by default.

**Comment by jsandoe** [comment]
Am merging this PR so it can make the next CODAP build.

**Pull request merged**
